name: CI/CD Pipeline

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.10

            - name: Install dependencies
              run: |
                pip install -r requirements.txt

            - name: Run basic tests
              run: |
                echo "Running tests (none yet)"

            - name: Build Docker image with BuildKit
              env:
                DOCKER_BUILDKIT: 1
              run: |
                docker build -t flask-devops-app .